
<html>
<head>
<title> Cat Scheule</title>
	<link rel="stylesheet" type="text/css" href="public/css/style.css">
</head>
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<a href="#"class="navbar-brand">Schedule</a>
		<ul class="nav navbar-nav" >
			<li>
				<a href="#">Home</a>
			</li>
			
			<li>
				<a href="#">Sign In</a>
			</li>
			<li>
				<a href="#">Assign Shift</a>
			</li>
			<li>
				<a href="#">Drop Shift</a>
			</li>
		</ul>
	</div>
</nav>